# Generated by Django 3.1.7 on 2021-05-11 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210507_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
